# Generated by Django 5.1 on 2024-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrera",
            name="duracion",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
