# Generated by Django 5.1 on 2024-08-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="telefono",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
