# Generated by Django 5.1 on 2024-10-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumno", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="habilitado",
            field=models.BooleanField(default=True),
        ),
    ]
