# Generated by Django 5.1 on 2024-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("dni", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("titulo", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
