# Generated by Django 5.1 on 2024-09-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
