# Generated by Django 5.1 on 2024-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0003_remove_usuario_last_login_remove_usuario_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
