# Generated by Django 5.1 on 2024-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrera", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrera",
            name="especialidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ingenieria", "Ingenieria"),
                    ("Medicina", "Medicina"),
                    ("Arte", "Arte"),
                    ("Derecho", "Derecho"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
