# Generated by Django 5.1 on 2024-11-08 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alumno", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumno",
            name="edad",
        ),
    ]
